name: review_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - cloudpickle==3.0.0
  - mlflow==2.15.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - pandas==2.2.2
  - matplotlib==3.9.1
  - seaborn==0.13.2
  - joblib==1.4.2
  - Flask==3.0.3
  - requests==2.31.0
  - pip
  - pip:
    - transformers==4.42.4
    - torch==2.3.1
    - tensorflow==2.16.2











